[project]
name = "doby"
version = "0.1.0"
description = "Flask tutorial app modified for plotting graphs."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
